${ANDROID_CMAKE_HOME}/bin/cmake . \
-DCMAKE_INSTALL_PREFIX=build \
-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
-DANDROID_ABI=arm64-v8a \
-DANDROID_PLATFORM=21 \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_FORCE_ARM_BUILD=TRUE \
-DANDROID_STL=c++_shared